api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json:
            mime_types:
                - application/json
    
    error_formats:
        json:
            mime_types:
                - application/json

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    
    graphql:
        enabled: false
