framework:
    messenger:
        failure_transport: failed

        transports:
            # Canal asynchrone qui utilise la base de données pour le développement
            async: 'doctrine://default'
            # Canal pour les messages qui ont échoué
            failed: 'doctrine://default?queue_name=failed'

        routing:
            # On route nos classes de message vers le canal asynchrone
            'App\Message\MessageHandler\RegisterNewMission\RegisterNewMissionData': async
            'App\Message\MessageHandler\RegisterNewMissionWithShift\RegisterNewMissionWithShiftData': async
            'App\Message\MessageHandler\RegisterDeleteMission\RegisterDeleteMissionData': async
            'App\Message\MessageHandler\RegisterUpdateMissionWithShift\RegisterUpdateMissionWithShiftData': async
            'App\Message\MessageHandler\RegisterNewUser\RegisterNewUserData': async

# Configuration spécifique pour l'environnement de test
when@test:
    framework:
        messenger:
            transports:
                # En test, les messages sont stockés en mémoire et non envoyés.
                # Cela permet de vérifier qu'ils ont bien été émis.
                async: 'in-memory://'