framework:
    rate_limiter:
        login:
            policy: 'fixed_window' # Protection Brut force 
            limit: 5              # 5 tentatives max
            interval: '5 minutes'  # Réinitialisation toutes minutes
        
        refresh_token:
            policy: 'token_bucket'
            limit: 30             # 10 refresh max
            rate: { interval: '1 hour', amount: 10 }  # 10 requêtes/heure max