framework:
    rate_limiter:
        login:
            policy: 'fixed_window' # Protection Brut force 
            limit: 6              # 6 tentatives 
            interval: '15 minutes'  # Réinitialisation toutes les 15 minutes
        
        refresh_token:
            policy: 'sliding_window'
            limit: 20             # 20 refresh
            interval: '10 hours'  